'use client';

// Public entry point for the map. Leaflet touches `window` at import time, so
// the real implementation (MapViewInner) is loaded with `next/dynamic` and
// `ssr: false`; a pulsing skeleton fills the container meanwhile.

import dynamic from 'next/dynamic';
import { preconnect, prefetchDNS } from 'react-dom';
import type { ControlPosition } from 'leaflet';
import type { Depot, Driver, Route, Stop } from '@/lib/types';

const OSM_TILE_ORIGIN = 'https://tile.openstreetmap.org';

/** Props for the RouteIQ map (contract shared with the dispatcher + driver pages). */
/**
 * Padding for the fit-to-all-stops framing. Either symmetric `[x, y]` or
 * asymmetric `{ topLeft, bottomRight }` — the latter lets a page keep the
 * markers above a fixed bottom sheet (`bottomRight: [x, sheetHeight + x]`).
 */
export type FitPadding =
  | [number, number]
  | { topLeft: [number, number]; bottomRight: [number, number] };

/**
 * Pixels of the map container hidden under page overlays (a bottom sheet, a
 * floating bar). Marker popups pan into the uncovered part instead of opening
 * under the overlay. Both edges default to 0.
 */
export interface MapViewportInset {
  bottom?: number;
  top?: number;
}

export interface MapViewProps {
  depot: Depot;
  stops: Stop[];
  drivers: Driver[];
  routes: Route[] | null;
  /** Routes/stops of these drivers are not drawn (legend toggles). */
  hiddenDriverIds?: string[];
  /** Opens/highlights this stop's popup; pans to it when off-screen. */
  selectedStopId?: string | null;
  onSelectStop?: (stopId: string | null) => void;
  /** When provided the stop popup shows a "Reassign to…" driver select. */
  onReassign?: (stopId: string, toDriverId: string) => void;
  /**
   * DRIVER MODE: fit bounds to this leg, draw it bold, draw the rest of that
   * driver's route faint, hide other drivers. `fromId` / `toId` are stop ids
   * or `'DEPOT'`.
   */
  focus?: { driverId: string; fromId: string; toId: string } | null;
  /** When this value changes the map re-fits to all visible stops + depot (dispatch mode). */
  fitKey?: string | number;
  /** Numbered 1..N markers along each route (default true when routes exist). */
  showSequenceNumbers?: boolean;
  /** Applied to the outer container (the parent must give it a height). */
  className?: string;

  // --- Optional extras (not part of the cross-module contract) -------------
  /** Padding used by fit-to-bounds in dispatch mode. Default `[32, 32]`. */
  fitPadding?: FitPadding;
  /** Where the +/- zoom control sits. Default `'topright'` (bottom is covered by sheets on mobile). */
  zoomControlPosition?: ControlPosition;
  /** Where the OSM attribution sits. Default `'bottomright'`. */
  attributionPosition?: ControlPosition;
  /** Draw direction arrows along routes in dispatch mode. Default true. */
  showDirectionArrows?: boolean;
  /**
   * Overlay-covered strips of the map (px). The selected stop's popup is
   * panned into the uncovered area (dispatch: the mobile bottom sheet).
   */
  viewportInset?: MapViewportInset;
}

/**
 * Shown while the Leaflet bundle loads: a slate-toned, abstract "map coming"
 * silhouette (public/map-placeholder.webp, ~6 KB, generated by
 * scripts/generate-map-placeholder.mjs — a raster on purpose: an SVG in an
 * <img> paints on the main thread, which is busy booting the app). Because it is real HTML content it
 * paints at first paint and, on phones, is the page's largest element — so the
 * Largest Contentful Paint lands at first paint instead of at the first map
 * tile, which can only appear after Leaflet has booted.
 */
export function MapSkeleton({ decorative = false }: { decorative?: boolean } = {}) {
  // OSM tiles are the map's LCP image, so open the connection while Leaflet is
  // still downloading. React hoists both hints into <head> of the server HTML,
  // which keeps them on map pages only (the landing page never renders this).
  preconnect(OSM_TILE_ORIGIN, { crossOrigin: 'anonymous' });
  prefetchDNS(OSM_TILE_ORIGIN);

  // `decorative`: the caller already wraps this in its own live "loading"
  // region (the driver screen skeleton) — a nested role=status would make
  // screen readers announce the same thing twice.
  const a11y = decorative
    ? { 'aria-hidden': true as const }
    : { role: 'status', 'aria-busy': true as const, 'aria-live': 'polite' as const, 'aria-label': 'Loading map' };
  return (
    <div className="relative h-full w-full overflow-hidden bg-slate-200" {...a11y}>
      {/* Plain <img> on purpose: a 6 KB static asset with an intrinsic size that
          must be in the SSR HTML with fetchpriority=high + sync decode; next/image
          would add its loader/lazy-loading machinery for no benefit here. */}
      {/* eslint-disable-next-line @next/next/no-img-element */}
      <img
        src="/map-placeholder.webp"
        alt=""
        aria-hidden="true"
        // Sync decode (it is ~6 KB): the image joins the very first paint frame
        // instead of waiting for a later frame that the JS boot would block.
        decoding="sync"
        // It is the LCP element: don't let it queue behind the JS either.
        fetchPriority="high"
        className="riq-map-placeholder h-full w-full object-cover"
        width={375}
        height={600}
      />
    </div>
  );
}

/**
 * Client-only Leaflet map. Renders `MapSkeleton` until the Leaflet bundle has
 * loaded in the browser.
 */
// Kick off the Leaflet chunk download as soon as a page that uses the map
// evaluates (i.e. in parallel with hydration) instead of waiting until the
// first <MapView /> render. `dynamic()` below resolves the
// same module from cache. Client-only guard: this module is also evaluated on
// the server for the SSR pass of pages that import it.
if (typeof window !== 'undefined') {
  void import('./MapViewInner');
}

const MapView = dynamic<MapViewProps>(() => import('./MapViewInner'), {
  ssr: false,
  loading: () => <MapSkeleton />,
});

export default MapView;
